### ISSUE TITLE
楼主,能说下你怎么部署的么

### ISSUE THREAD

**Issue by daowolf** [love3forever/gogo3#18]

**Comment by daowolf** [comment]
楼主你能详细的说下你是怎么部署的么

**Comment by love3forever** [comment]
不好意思，刚看到这个issue，这个项目已经很久不更新了
现在的后端数据服务部署方式是这样的：
1. 用到了fabric，[fabric脚本](https://github.com/love3forever/gogo3/blob/master/src/backend/fabfile.py)可以在连接远程主机，完成代码更新；
2. 代码拉取之后，启动python进程

前端代码在build之后，生成的静态文件直接用nginx发布出来即可
